language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - ruby-head
  - jruby-9.2.5.0
before_install:
  - gem update --system
  - gem install bundler --no-document
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
